name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  MacOS:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cd transform && cargo test -- --nocapture

  Windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cd transform && cargo test -- --nocapture
